name = "glam"
version = "2.0.3"
description = "A package to help you easily pretty print structured data"

licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "glam" }

[dependencies]
gleam_stdlib = ">= 0.62.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.1 and < 2.0.0"
birdie = ">= 1.3.2 and < 2.0.0"

[documentation]
pages = [
    { title = "Learning materials", path = "learning_materials.html", source = "./tutorials/README.md" },
    { title = "", path = "pretty_printing_glamorous_lists.html", source = "./tutorials/pretty_printing_glamorous_lists.md" },
    { title = "", path = "pretty_printing_todo_lists.html", source = "./tutorials/pretty_printing_todo_lists.md" },
    { title = "", path = "pretty_printing_JSON.html", source = "./tutorials/pretty_printing_JSON.md" },
    { title = "", path = "pretty_printing_lovely_error_messages.html", source = "./tutorials/pretty_printing_lovely_error_messages.md" },
]
