name = "glam"
version = "1.2.0"
description = "A package to help you easily pretty print structured data"

licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "glam" }
internal_modules = ["examples", "examples/*"]

[dependencies]
gleam_stdlib = "~> 0.31"

[dev-dependencies]
gleeunit = "~> 0.10"

[documentation]
pages = [
  { title = "Learning materials", path = "learning_materials.html", source = "./tutorials/README.md" },
  { title = "", path = "pretty_printing_glamorous_lists.html", source = "./tutorials/pretty_printing_glamorous_lists.md" },
  { title = "", path = "pretty_printing_todo_lists.html", source = "./tutorials/pretty_printing_todo_lists.md" },
  { title = "", path = "pretty_printing_JSON.html", source = "./tutorials/pretty_printing_JSON.md" },
  { title = "", path = "pretty_printing_lovely_error_messages.html", source = "./tutorials/pretty_printing_lovely_error_messages.md" },
]
